micronaut:
  application:
    name: cadastroRest
  server:
    port: ${SERVER_PORT:8080}
  security:
    authentication: cookie
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: http://localhost:8888/auth/realms/cadastro/protocol/openid-connect/certs
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    manager:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10





